if ("`whoami`" == "root") then
    set Prompt="# "
else
    set Prompt="% "
endif

if ($?tcsh) then
 set prompt = "%m [%c3]$Prompt"
else
  alias setprompt set prompt = '"`hostname` [$cwd]${Prompt}"'
  alias cd chdir \!\#\* \; setprompt
  setprompt
endif

umask 002
sudo /bin/chown gradle /run/host-services/ssh-auth.sock
sudo /bin/chown gradle /var/run/docker.sock
/opt/zfin/source_roots/zfin.org/docker/compile/generate_base.sh
cd /opt/zfin/source_roots/zfin.org
# uncomment for doing custom local things in docker (eg. set TARGETROOT and SOURCEROOT to the same)
#source commons/env/docker-local.env
#
source commons/env/docker.env
