#!/usr/bin/env groovy
// mk-zenv.groovy -- generate a ".zenv/" (venv-style activation) for a Docker Compose stack.
//
// Creates <dir>/.zenv/activate + <dir>/.zenv/bin/. Then:
//     source <dir>/.zenv/activate
// puts the z-commands (zrun/zexec/zup/zdown/zpull/zlog/zrestart/zstatus/zhelp) on PATH
// and points them -- plus bare `docker compose` -- at the given stack via
// COMPOSE_PROJECT_NAME / COMPOSE_FILE / COMPOSE_ENV_FILES, so you never type
// -p/--env-file/-f. `deactivate` restores the shell. This replaces the old global
// install: there is no copy of zrun on PATH; you `source .zenv/activate` once per session.
//
// The z-commands are symlinks into THIS repo's docker/utils/zrun (the single real
// script), so .zenv/bin/ carries no logic of its own and never drifts.
//
// Usage:
//   mk-zenv.groovy --dir DIR --project NAME --compose F1[:F2...] --env-file ENV [--tag TAG] [--host HOST]
//
//   --dir DIR        Where to create .zenv/ (worktree or repo root)
//   --project NAME   COMPOSE_PROJECT_NAME for the stack
//   --compose LIST   ':'-separated compose file(s) (base[:overlay])
//   --env-file ENV   env file for the stack (COMPOSE_ENV_FILES)
//   --tag TAG        PRELOADED_TAG to export (optional; omit for the base stack)
//   --host HOST      hostname for the activation banner URL (optional)

import java.nio.file.Files
import java.nio.file.Paths

def die = { String m, int c = 1 -> System.err.println("mk-zenv: $m"); System.exit(c) }
String capOut(List cmd) {
    def p = new ProcessBuilder(cmd*.toString()).redirectError(ProcessBuilder.Redirect.DISCARD).start()
    def o = p.inputStream.text; p.waitFor(); o.trim()
}

def SELF  = new File(getClass().protectionDomain.codeSource.location.toURI())
def UTILS = SELF.parentFile.absoluteFile          // docker/utils (holds the real zrun)
def ZRUN  = new File(UTILS, 'zrun')
def ALIASES = ['zexec', 'zrestart', 'zup', 'zdown', 'zpull', 'zlog', 'zstatus', 'zhelp']

// --- args --------------------------------------------------------------------
def opt = [:]
def argv = args as List
for (int i = 0; i < argv.size(); i++) {
    switch (argv[i]) {
        case '--dir':      opt.dir = argv[++i];     break
        case '--project':  opt.project = argv[++i]; break
        case '--compose':  opt.compose = argv[++i]; break
        case '--env-file': opt.envFile = argv[++i]; break
        case '--tag':      opt.tag = argv[++i];     break
        case '--host':     opt.host = argv[++i];    break
        default: die("unknown arg: ${argv[i]}", 2)
    }
}
['dir', 'project', 'compose', 'envFile'].each {
    if (!opt[it]) die("--dir, --project, --compose, --env-file are required", 2)
}
if (!ZRUN.isFile()) die("real zrun not found at $ZRUN")
def dir = new File(opt.dir.toString()).absoluteFile
if (!dir.isDirectory()) die("--dir '$dir' is not a directory")

def zenv = new File(dir, '.zenv')
def bin  = new File(zenv, 'bin')
bin.mkdirs()

// bin/: zrun -> the one real script (absolute); aliases -> zrun (relative). zrun
// dispatches on its invoked basename, so the aliases just work via those names.
def ln = { File link, String target ->
    Files.deleteIfExists(link.toPath())
    Files.createSymbolicLink(link.toPath(), Paths.get(target))
}
ln(new File(bin, 'zrun'), ZRUN.absolutePath)
ALIASES.each { ln(new File(bin, it), 'zrun') }
// zfeature is a separate real script (not a zrun basename-alias), so link it directly.
ln(new File(bin, 'zfeature'), new File(UTILS, 'zfeature').absolutePath)

// activate: a header of baked values + a literal bash body (env save/set + deactivate).
def header = """\
# .zenv/activate for '${opt.project}'. Source me:  source .zenv/activate
# Generated by mk-zenv.groovy -- re-run it to regenerate; don't hand-edit.
_ZENV_PROJECT='${opt.project}'
_ZENV_HOST='${opt.host ?: ''}'
_ZENV_DIR='${dir.absolutePath}'
_ZENV_BIN='${bin.absolutePath}'
_ZENV_COMPOSE_FILE='${opt.compose}'
_ZENV_ENV_FILE='${opt.envFile}'
_ZENV_TAG='${opt.tag ?: ''}'
"""
def body = '''\
if command -v deactivate >/dev/null 2>&1 && [ -n "${ZENV_ACTIVE:-}" ]; then deactivate; fi

_ZENV_OLD_PS1="${PS1:-}"
_ZENV_OLD_PATH="$PATH"
_ZENV_OLD_CPN="${COMPOSE_PROJECT_NAME:-}"
_ZENV_OLD_CPNS="${COMPOSE_PROJECT_NAMES:-}"
_ZENV_OLD_CF="${COMPOSE_FILE:-}"
_ZENV_OLD_CEF="${COMPOSE_ENV_FILES:-}"
_ZENV_OLD_TAG="${PRELOADED_TAG:-}"

export PATH="$_ZENV_BIN:$PATH"
export COMPOSE_PROJECT_NAME="$_ZENV_PROJECT"
export COMPOSE_PROJECT_NAMES="$_ZENV_PROJECT"
export COMPOSE_FILE="$_ZENV_COMPOSE_FILE"
export COMPOSE_ENV_FILES="$_ZENV_ENV_FILE"
[ -n "$_ZENV_TAG" ] && export PRELOADED_TAG="$_ZENV_TAG"
export ZENV_ACTIVE="$_ZENV_PROJECT"
export ZENV_HOST="$_ZENV_HOST"
export ZENV_DIR="$_ZENV_DIR"

PS1="($_ZENV_PROJECT) ${PS1:-}"

deactivate() {
  PATH="$_ZENV_OLD_PATH"; export PATH
  PS1="$_ZENV_OLD_PS1"
  if [ -n "$_ZENV_OLD_CPN" ];  then export COMPOSE_PROJECT_NAME="$_ZENV_OLD_CPN";   else unset COMPOSE_PROJECT_NAME;  fi
  if [ -n "$_ZENV_OLD_CPNS" ]; then export COMPOSE_PROJECT_NAMES="$_ZENV_OLD_CPNS"; else unset COMPOSE_PROJECT_NAMES; fi
  if [ -n "$_ZENV_OLD_CF" ];   then export COMPOSE_FILE="$_ZENV_OLD_CF";            else unset COMPOSE_FILE;          fi
  if [ -n "$_ZENV_OLD_CEF" ];  then export COMPOSE_ENV_FILES="$_ZENV_OLD_CEF";      else unset COMPOSE_ENV_FILES;     fi
  if [ -n "$_ZENV_OLD_TAG" ];  then export PRELOADED_TAG="$_ZENV_OLD_TAG";          else unset PRELOADED_TAG;         fi
  unset ZENV_ACTIVE ZENV_HOST ZENV_DIR
  unset _ZENV_PROJECT _ZENV_HOST _ZENV_DIR _ZENV_BIN _ZENV_COMPOSE_FILE _ZENV_ENV_FILE _ZENV_TAG
  unset _ZENV_OLD_PS1 _ZENV_OLD_PATH _ZENV_OLD_CPN _ZENV_OLD_CPNS _ZENV_OLD_CF _ZENV_OLD_CEF _ZENV_OLD_TAG
  unset -f deactivate
  echo "zenv: deactivated (restored previous shell environment)"
}

if [ -n "$_ZENV_HOST" ]; then
  echo "zenv: activated $_ZENV_PROJECT  ->  https://$_ZENV_HOST   (z-commands on PATH; 'deactivate' to exit)"
else
  echo "zenv: activated $_ZENV_PROJECT   (z-commands on PATH; 'deactivate' to exit)"
fi
'''
new File(zenv, 'activate').text = header + body

// Keep .zenv/ out of git without touching a tracked .gitignore (works on any branch).
def common = capOut(['git', '-C', dir.absolutePath, 'rev-parse', '--git-common-dir'])
if (common) {
    def cdir = new File(common).isAbsolute() ? new File(common) : new File(dir, common)
    def excl = new File(cdir, 'info/exclude')
    def existing = excl.exists() ? excl.text : ''
    if (!(existing =~ /(?m)^\.zenv\/\s*$/)) {
        excl.parentFile.mkdirs()
        excl << (existing && !existing.endsWith('\n') ? '\n' : '')
        excl << '.zenv/\n'
    }
}

println "mk-zenv: wrote $zenv  ->  source ${new File(zenv, 'activate')}"
