// CreateZenv -- generate a ".zenv/" (venv-style activation) for a Docker Compose stack.
//
// Creates <dir>/.zenv/activate + <dir>/.zenv/bin/z. Then:
//     source <dir>/.zenv/activate
// puts `z` on PATH and defines the short-name shell functions (zrun/zexec/zup/zdown/zpull/
// zlog/zrestart/zstatus/zhelp/zfeature/zbuild -> `z run`/`z exec`/...), and points them --
// plus bare `docker compose` -- at the given stack via COMPOSE_PROJECT_NAME / COMPOSE_FILE /
// COMPOSE_ENV_FILES, so you never type -p/--env-file/-f. `deactivate` restores the shell.
//
// bin/ holds a single symlink `z` -> docker/utils/z (the only executable). The short names
// are shell FUNCTIONS (not symlinks) because a Groovy `z` can't see which name invoked it.
// Run via `z create-zenv ...` (bootstrap) -- $ZFIN_UTILS comes from z.
//
// Usage:
//   z create-zenv --dir DIR --project NAME --compose F1[:F2...] --env-file ENV [--tag TAG] [--host HOST]
//
//   --dir DIR        Where to create .zenv/ (worktree or repo root)
//   --project NAME   COMPOSE_PROJECT_NAME for the stack
//   --compose LIST   ':'-separated compose file(s) (base[:overlay])
//   --env-file ENV   env file for the stack (COMPOSE_ENV_FILES)
//   --tag TAG        PRELOADED_TAG to export (optional; omit for the base stack)
//   --host HOST      hostname for the activation banner URL (optional)

import java.nio.file.Files
import java.nio.file.Paths

class CreateZenv {
    def run(List args, ZfinUtil zfinUtil) {
        def die = zfinUtil.&die
        def captureOutput = zfinUtil.&captureOutput
        def ZFRONT = new File(zfinUtil.UTILS, 'z')   // the one executable every stack activates
        def LIB = zfinUtil.LIB                      // docker/utils/lib (holds z-completion.bash)

// --- args --------------------------------------------------------------------
        def opt = [:]
        def argv = args as List
        for (int i = 0; i < argv.size(); i++) {
            switch (argv[i]) {
                case '--dir': opt.dir = argv[++i]; break
                case '--project': opt.project = argv[++i]; break
                case '--compose': opt.compose = argv[++i]; break
                case '--env-file': opt.envFile = argv[++i]; break
                case '--tag': opt.tag = argv[++i]; break
                case '--host': opt.host = argv[++i]; break
                default: die("unknown arg: ${argv[i]}", 2)
            }
        }
        ['dir', 'project', 'compose', 'envFile'].each {
            if (!opt[it]) die("--dir, --project, --compose, --env-file are required", 2)
        }
        if (!ZFRONT.isFile()) die("front door not found at $ZFRONT")
        def dir = new File(opt.dir.toString()).absoluteFile
        if (!dir.isDirectory()) die("--dir '$dir' is not a directory")

        def zenv = new File(dir, '.zenv')
        def bin = new File(zenv, 'bin')
// Recreate bin/ fresh: clear any stale symlinks left by an older tooling layout (e.g. the
// per-short-name symlinks that predate the single-front-door model).
        if (bin.isDirectory()) bin.listFiles().each { it.delete() }
        bin.mkdirs()

// bin/: a single `z` symlink -> the front door. Short names are functions (see activate).
        Files.createSymbolicLink(new File(bin, 'z').toPath(), Paths.get(ZFRONT.absolutePath))

// activate: comment + a switch-guard + baked vars + a literal bash body. ORDER MATTERS:
// the switch-guard (deactivate a currently-active .zenv) must run BEFORE the baked vars
// are set -- the old deactivate() unsets the _ZENV_* names, so if it ran after, it would
// wipe the fresh values and activation would come up empty (broke re-sourcing/switching).
        def comment = """\
# .zenv/activate for '${opt.project}'. Source me:  source .zenv/activate
# Generated by create-zenv.groovy -- re-run it to regenerate; don't hand-edit.
"""
        def switchGuard = '''\
if command -v deactivate >/dev/null 2>&1 && [ -n "${ZENV_ACTIVE:-}" ]; then deactivate; fi
'''
        def vars = """\
_ZENV_PROJECT='${opt.project}'
_ZENV_HOST='${opt.host ?: ''}'
_ZENV_DIR='${dir.absolutePath}'
_ZENV_BIN='${bin.absolutePath}'
_ZENV_LIB='${LIB.absolutePath}'
_ZENV_COMPOSE_FILE='${opt.compose}'
_ZENV_ENV_FILE='${opt.envFile}'
_ZENV_TAG='${opt.tag ?: ''}'
"""
        def body = '''\
_ZENV_OLD_PS1="${PS1:-}"
_ZENV_OLD_PATH="$PATH"
_ZENV_OLD_CPN="${COMPOSE_PROJECT_NAME:-}"
_ZENV_OLD_CF="${COMPOSE_FILE:-}"
_ZENV_OLD_CEF="${COMPOSE_ENV_FILES:-}"
_ZENV_OLD_TAG="${PRELOADED_TAG:-}"

export PATH="$_ZENV_BIN:$PATH"
export COMPOSE_PROJECT_NAME="$_ZENV_PROJECT"
export COMPOSE_FILE="$_ZENV_COMPOSE_FILE"
export COMPOSE_ENV_FILES="$_ZENV_ENV_FILE"
[ -n "$_ZENV_TAG" ] && export PRELOADED_TAG="$_ZENV_TAG"
export ZENV_ACTIVE="$_ZENV_PROJECT"
export ZENV_HOST="$_ZENV_HOST"
export ZENV_DIR="$_ZENV_DIR"

PS1="($_ZENV_PROJECT) ${PS1:-}"

# Short-name shell functions -> the one `z` on PATH.
zrun()     { z run "$@"; }
zexec()    { z exec "$@"; }
zup()      { z up "$@"; }
zdown()    { z down "$@"; }
zpull()    { z pull "$@"; }
zlog()     { z log "$@"; }
zrestart() { z restart "$@"; }
zstatus()  { z status "$@"; }
zhelp()    { z help "$@"; }
zfeature() { z feature "$@"; }
zbuild()   { z build "$@"; }

# bash tab-completion for z + the short names (no-op in other shells / if missing)
if [ -n "${BASH_VERSION:-}" ] && [ -r "$_ZENV_LIB/z-completion.bash" ]; then
  . "$_ZENV_LIB/z-completion.bash"
fi

deactivate() {
  PATH="$_ZENV_OLD_PATH"; export PATH
  PS1="$_ZENV_OLD_PS1"
  if [ -n "$_ZENV_OLD_CPN" ]; then export COMPOSE_PROJECT_NAME="$_ZENV_OLD_CPN"; else unset COMPOSE_PROJECT_NAME; fi
  if [ -n "$_ZENV_OLD_CF" ];  then export COMPOSE_FILE="$_ZENV_OLD_CF";          else unset COMPOSE_FILE;         fi
  if [ -n "$_ZENV_OLD_CEF" ]; then export COMPOSE_ENV_FILES="$_ZENV_OLD_CEF";    else unset COMPOSE_ENV_FILES;    fi
  if [ -n "$_ZENV_OLD_TAG" ]; then export PRELOADED_TAG="$_ZENV_OLD_TAG";        else unset PRELOADED_TAG;        fi
  unset -f zrun zexec zup zdown zpull zlog zrestart zstatus zhelp zfeature zbuild 2>/dev/null || true
  complete -r z zrun zexec zup zdown zpull zlog zrestart zstatus zhelp zfeature zbuild 2>/dev/null || true
  unset ZENV_ACTIVE ZENV_HOST ZENV_DIR
  unset _ZENV_PROJECT _ZENV_HOST _ZENV_DIR _ZENV_BIN _ZENV_LIB _ZENV_COMPOSE_FILE _ZENV_ENV_FILE _ZENV_TAG
  unset _ZENV_OLD_PS1 _ZENV_OLD_PATH _ZENV_OLD_CPN _ZENV_OLD_CF _ZENV_OLD_CEF _ZENV_OLD_TAG
  unset -f deactivate
  echo "zenv: deactivated (restored previous shell environment)"
}

if [ -n "$_ZENV_HOST" ]; then
  echo "zenv: activated $_ZENV_PROJECT  ->  https://$_ZENV_HOST   (z-commands on PATH; 'deactivate' to exit)"
else
  echo "zenv: activated $_ZENV_PROJECT   (z-commands on PATH; 'deactivate' to exit)"
fi
'''
        new File(zenv, 'activate').text = comment + switchGuard + vars + body

// Keep .zenv/ out of git without touching a tracked .gitignore (works on any branch).
        def common = captureOutput(['git', '-C', dir.absolutePath, 'rev-parse', '--git-common-dir'])
        if (common) {
            def cdir = new File(common).isAbsolute() ? new File(common) : new File(dir, common)
            def excl = new File(cdir, 'info/exclude')
            def existing = excl.exists() ? excl.text : ''
            if (!(existing =~ /(?m)^\.zenv\/\s*$/)) {
                excl.parentFile.mkdirs()
                excl << (existing && !existing.endsWith('\n') ? '\n' : '')
                excl << '.zenv/\n'
            }
        }

        println "create-zenv: wrote $zenv  ->  source ${new File(zenv, 'activate')}"
    }
}
